// export const themes = [
// 	"light",
// 	"dark",
// 	"cupcake",
// 	"bumblebee",
// 	"emerald",
// 	"corporate",
// 	"synthwave",
// 	"retro",
// 	"cyberpunk",
// 	"valentine",
// 	"halloween",
// 	"garden",
// 	"forest",
// 	"aqua",
// 	"lofi",
// 	"pastel",
// 	"fantasy",
// 	"wireframe",
// 	"black",
// 	"luxury",
// 	"dracula",
// 	"cmyk",
// 	"autumn",
// 	"business",
// 	"acid",
// 	"lemonade",
// 	"night",
// 	"coffee",
// 	"winter"
// ];

export const themes = [
	{ title: "Light (default)", theme: "light", type: "light" },
	{ title: "Dark (default)", theme: "dark", type: "dark" },
	{ title: "Cupcake (light)", theme: "cupcake", type: "light" },
	{ title: "Bumblebee (light)", theme: "bumblebee", type: "light" },
	{ title: "Emerald (light)", theme: "emerald", type: "light" },
	{ title: "Corporate (light)", theme: "corporate", type: "light" },
	{ title: "Garden (light)", theme: "garden", type: "light" },
	{ title: "Lofi (light)", theme: "lofi", type: "light" },
	{ title: "Pastel (light)", theme: "pastel", type: "light" },
	{ title: "Fantasy (light)", theme: "fantasy", type: "light" },
	{ title: "Wireframe (light)", theme: "wireframe", type: "light" },
	{ title: "CMYK (light)", theme: "cmyk", type: "light" },
	{ title: "Autumn (light)", theme: "autumn", type: "light" },
	{ title: "Acid (light)", theme: "acid", type: "light" },
	{ title: "Lemonade (light)", theme: "lemonade", type: "light" },
	{ title: "Winter (light)", theme: "winter", type: "light" },
	{ title: "Synthwave (dark)", theme: "synthwave", type: "dark" },
	{ title: "Halloween (dark)", theme: "halloween", type: "dark" },
	{ title: "Forest (dark)", theme: "forest", type: "dark" },
	{ title: "Black (dark)", theme: "black", type: "dark" },
	{ title: "Luxury (dark)", theme: "luxury", type: "dark" },
	{ title: "Dracula (dark)", theme: "dracula", type: "dark" },
	{ title: "Business (dark)", theme: "business", type: "dark" },
	{ title: "Night (dark)", theme: "night", type: "dark" },
	{ title: "Coffee (dark)", theme: "coffee", type: "dark" },
	{ title: "Retro (color)", theme: "retro", type: "light" },
	{ title: "Cyberpunk (color)", theme: "cyberpunk", type: "light" },
	{ title: "Valentine (color)", theme: "valentine", type: "light" },
	{ title: "Aqua (color)", theme: "aqua", type: "dark" }
];
